import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";

import "@/styles/globals.css";
import { cn } from "@/lib/utils";
import Navbar from "@/components/shared/Navbar";
import { WalletProviders } from "@/providers/WalletProviders";
import "@rainbow-me/rainbowkit/styles.css";

export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark" suppressHydrationWarning>
      <body
        className={cn(
          "min-h-screen font-sans antialiased bg-background",
          fontSans.variable
        )}>
        <WalletProviders>
          <Navbar />
          {children}
        </WalletProviders>
      </body>
    </html>
  );
}
